name: NAStool Package
on:
  workflow_dispatch:
    inputs:
      github_token:
        description: 'github token'
        required: true
        default: ''

jobs:
  Windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository code  # 检出当前仓库的代码
      uses: actions/checkout@v3
      with:
        ref: fix_build_202501161457  # 检出指定的分支或标签 v3.6.2
      
    - name: Init Python 3.10.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Install dependent packages
      run: |
        echo --------- 当前路径 ---------
        pwd
        python -m pip install --upgrade pip
        pip install wheel numpy==1.23.5 pyparsing==3.0.9 wxpython==4.2.0 pyinstaller==5.7.0
        pip install -r requirements_old.txt
        pip install -r requirements.txt
        echo ("NASTOOL_CONFIG=D:/a/nas-tools-temp2/nas-tools-temp2/config/config.yaml") >> $env:GITHUB_ENV
        echo $env:NASTOOL_CONFIG
      shell: pwsh

    - name: Package through pyinstaller
      run: |
        echo --------- 当前文件夹内容 ---------
        dir # 确认代码在当前目录
        copy .\package\rely\upx.exe c:\hostedtoolcache\windows\python\3.10.11\x64\Scripts
        copy .\package\rely\hook-cn2an.py c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\pyinstaller\hooks
        copy .\package\rely\hook-zhconv.py c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\pyinstaller\hooks
        copy .\package\rely\hook-iso639.py c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\pyinstaller\hooks
        copy .\third_party.txt .\package
        copy .\package\rely\template.jinja2 c:\hostedtoolcache\windows\Python\3.10.11\x64\lib\site-packages\setuptools\_vendor\pyparsing\diagram
        xcopy .\web c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\web\ /e
        xcopy .\config c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\config\ /e
        xcopy .\scripts c:\hostedtoolcache\windows\python\3.10.11\x64\lib\site-packages\scripts\ /e
        cd package
        pyinstaller nas-tools.spec
        dir  D:/a/nas-tools-temp2/nas-tools-temp2/package/dist
      shell: pwsh

    - name: Upload windows file
      uses: actions/upload-artifact@v3
      with:
        name: windows
        path: D:/a/nas-tools-temp2/nas-tools-temp2/package/dist/nas-tools.exe
